### ISSUE TITLE
unexpected IllegalStateException  thrown from TSDB#multiFieldPut(Collection<MultiFieldPoint>, AbstractMultiFieldBatchPutCallback)

### ISSUE THREAD

**Issue by xiaowing** [aliyun/aliyun-tsdb-java-sdk#123]
**Version information**
* SDK version
0.3.5

**Bug description**
The following exception thrown when writing data with `TSDB#multiFieldPut(Collection<MultiFieldPoint>, AbstractMultiFieldBatchPutCallback)` continously.

`Request cannot be executed; I/O reactor status: STOPPED`

**Exception stacktrace (Optional)**

> java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
  at org.apache.http.util.Asserts.check(Asserts.java:46)
  at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
  at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
  at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
  at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
  at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:92)
  at com.aliyun.hitsdb.client.http.HttpClient.executeCallback(HttpClient.java:325)
  at com.aliyun.hitsdb.client.http.HttpClient.postToAddress(HttpClient.java:408)
  at com.aliyun.hitsdb.client.consumer.PointsCollectionPutRunnable.sendHttpRequest(PointsCollectionPutRunnable.java:139)
  at com.aliyun.hitsdb.client.consumer.PointsCollectionPutRunnable.run(PointsCollectionPutRunnable.java:72)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
  at java.lang.Thread.run(Thread.java:852)

**Comment by xiaowing** [comment]
similar issue: https://stackoverflow.com/questions/35350376/java-lang-illegalstateexception-request-cannot-be-executed-i-o-reactor-status

**Comment by xiaowing** [comment]
the root cause is the "by-design" behavior of HttpAsyncClient 4.x.
it brought up a discussion over how to detect the IoReactor status change in the elasticsearch LLRC, which has not reached an agreement yet:

https://github.com/elastic/elasticsearch/issues/49124

**Comment by xiaowing** [comment]
it turns out that an "NoClassdefFoundError" thrown in the application's callback implementation caused this issue.
as the discussion mentioned above, we cannot FIX this issue. however, we can enhance the log tracing if the IoReactor encountered some unexpected exception for quick debug
