### ISSUE TITLE
多值模型string field value cannot by empty

### ISSUE THREAD

**Issue by zceolrj** [aliyun/aliyun-tsdb-java-sdk#70]
用到了TSDB的多值模型，其中一个field写入字符串类型的数据，写入的是空字符串""，报如下错误
Exception in thread "main" java.lang.IllegalArgumentException: String field value can't be empty
  at com.aliyun.hitsdb.client.value.request.MultiFieldPoint.checkPoint(MultiFieldPoint.java:224)
  at com.aliyun.hitsdb.client.value.request.MultiFieldPoint$MetricBuilder.build(MultiFieldPoint.java:134)
  at com.aliyun.hitsdb.client.value.request.MultiFieldPoint$MetricBuilder.build(MultiFieldPoint.java:123)

**Comment by xiaowing** [comment]
该问题已经在 #73 修复，但是空字符串的支持不仅仅是SDK需要改造；在TSDB 服务端也需要改造，目前服务端的改造也已完成，新版本在云上发布后即会将该PR合入

敬请期待。

**Comment by xiaowing** [comment]
对于 Aliyun TSDB v2.6.3版本及之后版本的引擎适用
